services:
  - type: web
    name: buscadesp
    env: python
    plan: starter
    region: oregon
    # Vamos usar o mesmo passo pra instalar deps e rodar o app
    startCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python3 main.py
