services:
  - type: docker
    name: buscadesp
    plan: starter
    dockerfilePath: Dockerfile
    envVars:
      - key: SUPABASE_URL
      - key: SUPABASE_KEY
      - key: SECRET_KEY
      - key: TG_API_ID
      - key: TG_API_HASH
