services:
  - type: web
    name: buscadesp
    env: python
    plan: starter       # ou free
    region: oregon      # ajuste se precisar
    buildCommand: |
      pip install --upgrade pip
      pip install --cache-dir .pip-cache -r requirements.txt
    startCommand: |
      gunicorn main:app \
        --workers 4 \
        --worker-class uvicorn.workers.UvicornWorker \
        --bind 0.0.0.0:$PORT \
        --timeout 120
