services:
  - type: web
    name: buscadespdeploy
    env: python3
    region: oregon        # ou a região que você costuma usar
    plan: free            # ou "starter", se for o plano que você contratou
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      SUPABASE_URL: "https://myjoddcnjgugdabbmyrj.supabase.co"
      SUPABASE_KEY: "eyJhbgciOiJIUzi1NiIsInR5cCI6IkpXVCJ9..."
      SECRET_KEY: "buscadesp_is_lit_2025"
      API_ID: "28382442"
      API_HASH: "5f5cdede83eecadeef4234fc1bd095a5"
      PHONE: "+5551995788207"
      SESSION_NAME: "buscadesp_session"
      BOT_USERNAME: "@YanbuscaBot"
      BASE_URL: "https://buscadespdeploy.onrender.com"